// <auto-generated />
using GameReviewApi.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameReviewApi.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220331155812_AddToDb")]
    partial class AddToDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GameReviewApi.Domain.Entity.Authenticate.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("GameReviewApi.Domain.Entity.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameId"), 1L, 1);

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GameId");

                    b.ToTable("Game");

                    b.HasData(
                        new
                        {
                            GameId = 1,
                            GameName = "Assassin's Creed"
                        },
                        new
                        {
                            GameId = 2,
                            GameName = "Resident Evil"
                        },
                        new
                        {
                            GameId = 3,
                            GameName = "Devil May Cry"
                        });
                });

            modelBuilder.Entity("GameReviewApi.Domain.Entity.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenreId"), 1L, 1);

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<string>("GenreName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenreId");

                    b.HasIndex("GameId");

                    b.ToTable("Genre");

                    b.HasData(
                        new
                        {
                            GenreId = 1,
                            GameId = 1,
                            GenreName = "Action"
                        },
                        new
                        {
                            GenreId = 2,
                            GameId = 1,
                            GenreName = "RPG"
                        },
                        new
                        {
                            GenreId = 3,
                            GameId = 2,
                            GenreName = "Action"
                        },
                        new
                        {
                            GenreId = 4,
                            GameId = 2,
                            GenreName = "Horror"
                        },
                        new
                        {
                            GenreId = 5,
                            GameId = 2,
                            GenreName = "RPG"
                        },
                        new
                        {
                            GenreId = 6,
                            GameId = 3,
                            GenreName = "Action"
                        },
                        new
                        {
                            GenreId = 7,
                            GameId = 3,
                            GenreName = "Slasher"
                        });
                });

            modelBuilder.Entity("GameReviewApi.Domain.Entity.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"), 1L, 1);

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<string>("ShortStory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReviewId");

                    b.HasIndex("GameId");

                    b.ToTable("Review");

                    b.HasData(
                        new
                        {
                            ReviewId = 1,
                            GameId = 1,
                            Grade = 78,
                            ShortStory = "Главная сюжетная ветка разворачивается, как уже говорилось, вокруг Альтаира, не последнего человека в ордене Ассассинов, который на архиважном задании нехило так облажался, в результате чего один напарник погиб, другой стал калекой. И ладно бы, так Альтаир умудрился привести хвост из армии крестоносцев, то бишь тамплиеров, в свою крепость. За такой косяк Аль-Муалим, духовный наставник и глава всего ордена, выносит главному герою выговор, занесением нескольких сантиметров стали в брюшную полость, понижает в ранге и дает шанс исправиться, потому что во-первых, Альтаир хоть и подставил свою семью (читайте орден), но мастерством обделен не был, а во-вторых - ну главный герой же, нельзя его выпиливать в начале игры."
                        },
                        new
                        {
                            ReviewId = 2,
                            GameId = 1,
                            Grade = 85,
                            ShortStory = "Проиграв на боевой системе, разработчики вовсю оторвались на атмосферности и историчности игры. Средними веками, теми событиями веет так, что дух захватывает. Города выполнены детально, со всеми достопримечательностями. Очень красиво. Народ толпится у прилавков, глашатаи дерут глотки, прославляя Саллах - ад - Дина или Ричарда III. Это здорово."
                        },
                        new
                        {
                            ReviewId = 3,
                            GameId = 1,
                            Grade = 93,
                            ShortStory = "Музыкальное сопровождение тоже на высоте. С восточными нотками, так же атмосферно. Про графику тоже следует упомянуть.Она на высоте.Сделанная для того времени, она реалистична: одежда развевается, волны плещут.Красиво, в общем.Даже сейчас она(графика) смотрится достойно.Весьма достойно."
                        },
                        new
                        {
                            ReviewId = 4,
                            GameId = 2,
                            Grade = 59,
                            ShortStory = "Максимально скучная игра. Такой душноты я не ожидал от хоррора. Миллион часов надо бегать по замку, собирая всякие тарелочки. Я бросил это дело и удалил игру после 4 часов игры. Стрельбы никакой не дали. Нужно было убегать от неубиваемой дочери леди Диметреску. После этого снова тарелки. Поставлю 2 балла. Больше совесть не позволяет."
                        },
                        new
                        {
                            ReviewId = 5,
                            GameId = 2,
                            Grade = 98,
                            ShortStory = "Эта часть напрямую продолжает предыдущую. По сюжету как всегда все сначала запутанно, но это не плохо, так и должно быть. Истории боссов получились вообще по кайфу. Единственное, что не зашло, так это количество шутана. Тут прям на каждом шагу тебя кто-то ждет пачками. Хотя обычно Резидент — это больше про сюжет и стелс, а от хоррора тут вообще мало чего. Добавили торговца, что тоже очень удобно в прохождении. Отрываться вообще не хотелось, прям затягивает. Много всего понравилось, но для полной картины лучше пройти 7 часть"
                        },
                        new
                        {
                            ReviewId = 6,
                            GameId = 2,
                            Grade = 71,
                            ShortStory = "Прошёл игру пять раз и почти на 100%. Это не хоррор (кроме одного момента), а скорее шутер от первого лица. Владык не раскрывают, либо ищи одну записки в огромной локации, либо высматривай детали одежды и окружения. Боевая система как в RE7. А атмосфера лучшая часть игры, возможно из-за неё я и прошёл игру пять раз."
                        },
                        new
                        {
                            ReviewId = 7,
                            GameId = 3,
                            Grade = 39,
                            ShortStory = "Когда-то давно играл в Devil May Cry , но не помню какая была часть, играл тогда на Play Station 3 , но совсем не помню про что там было и как это было) Эта серия игры затянула, интересный сюжет, драчульки) Но самый низкий уровень игры, как по мне сделан, ну уж слииишком низко, боссы почти не чувствовались, ну возможно это и наоборот не плохо. В общем если хотите погореть, то самый низкий уровень не для вас)"
                        },
                        new
                        {
                            ReviewId = 8,
                            GameId = 3,
                            Grade = 93,
                            ShortStory = "Игра классная, как слешер. Сюжет вполне себе интересный. Нашёл два минуса довольно существенных - унылость локаций особенно во второй половине и кол-во боссов могло быть больше или проработанней. Эти минусы (особенно локации) кто бы не говорил очень влияют на восприятии игры. Поэтому такие вот дела. Игру рекомендую не только любителям кромсать всё живое, но и просто гомерам"
                        });
                });

            modelBuilder.Entity("GameReviewApi.Domain.Entity.Genre", b =>
                {
                    b.HasOne("GameReviewApi.Domain.Entity.Game", null)
                        .WithMany("Genres")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameReviewApi.Domain.Entity.Review", b =>
                {
                    b.HasOne("GameReviewApi.Domain.Entity.Game", null)
                        .WithMany("Reviews")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameReviewApi.Domain.Entity.Game", b =>
                {
                    b.Navigation("Genres");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
